# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ouya/ouya_1_1/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/ouya/ouya_1_1/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
        vendor/ouya/ouya_1_1/proprietary/bin/bt_firmware_loader.sh:system/bin/bt_firmware_loader.sh \
        vendor/ouya/ouya_1_1/proprietary/bin/rm_ts_server:system/bin/rm_ts_server \
        vendor/ouya/ouya_1_1/proprietary/bin/tf_daemon:system/bin/tf_daemon \
        vendor/ouya/ouya_1_1/proprietary/etc/asound.conf:system/etc/asound.conf \
        vendor/ouya/ouya_1_1/proprietary/etc/enctune.conf:system/etc/enctune.conf \
        vendor/ouya/ouya_1_1/proprietary/etc/model_frontal.xml:system/etc/model_frontal.xml \
        vendor/ouya/ouya_1_1/proprietary/etc/nvaudio_conf.xml:system/etc/nvaudio_conf.xml \
        vendor/ouya/ouya_1_1/proprietary/etc/nvcamera.conf:system/etc/nvcamera.conf \
        vendor/ouya/ouya_1_1/proprietary/etc/nvram_4330.txt:system/etc/nvram_4330.txt \
        vendor/ouya/ouya_1_1/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
        vendor/ouya/ouya_1_1/proprietary/etc/firmware/nvavp_aud_ucode.bin:system/etc/firmware/nvavp_aud_ucode.bin \
        vendor/ouya/ouya_1_1/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
        vendor/ouya/ouya_1_1/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
        vendor/ouya/ouya_1_1/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
        vendor/ouya/ouya_1_1/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libEGL_tegra_impl.so:system/lib/egl/libEGL_tegra_impl.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLESv1_CM_tegra_impl.so:system/lib/egl/libGLESv1_CM_tegra_impl.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLESv2_tegra_impl.so:system/lib/egl/libGLESv2_tegra_impl.so \
        vendor/ouya/ouya_1_1/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/hw/audio_policy.tegra.so:system/lib/hw/audio_policy.tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libaudioavp.so:system/lib/libaudioavp.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libmllite.so:system/lib/libmllite.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libsensors.mpl.so:system/lib/libsensors.mpl.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvaudioservice.so:system/lib/libnvaudioservice.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvcapclk.so:system/lib/libnvcapclk.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvcap.so:system/lib/libnvcap.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvcap_video.so:system/lib/libnvcap_video.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvglsi.so:system/lib/libnvglsi.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvos.so:system/lib/libnvos.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libsensors.base.so:system/lib/libsensors.base.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libsensors.isl29018.so:system/lib/libsensors.isl29018.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libsensors.isl29028.so:system/lib/libsensors.isl29028.so \
        vendor/ouya/ouya_1_1/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
        vendor/ouya/ouya_1_1/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
        vendor/ouya/ouya_1_1/proprietary/vendor/firmware/bcm4330/fw_bcmdhd_apsta.bin:system/vendor/firmware/bcm4330/fw_bcmdhd_apsta.bin \
        vendor/ouya/ouya_1_1/proprietary/vendor/firmware/bcm4330/fw_bcmdhd.bin:system/vendor/firmware/bcm4330/fw_bcmdhd.bin \
        vendor/ouya/ouya_1_1/proprietary/vendor/firmware/bcm4330/fw_bcmdhd_p2p.bin:system/vendor/firmware/bcm4330/fw_bcmdhd_p2p.bin
